os: linux
sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=codecov,docs-html
    - python: 3.5
      env: TOXENV=py,codecov
    - python: 3.4
      env: TOXENV=py,codecov
    - python: 2.7
      env: TOXENV=py,codecov
    - python: pypy
      env: TOXENV=py,codecov
    - python: nightly
      env: TOXENV=py
    - os: osx
      language: generic
      env: TOXENV=py
  allow_failures:
    - os: osx
      language: generic
      env: TOXENV=py
  fast_finish: true

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install python3 redis memcached;
        virtualenv -p python3 ~/py-env;
        . ~/py-env/bin/activate;
      fi
    # Travis uses an outdated PyPy, this installs a more recent one.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "pypy" ]]; then
        git clone https://github.com/pyenv/pyenv.git ~/.pyenv;
        PYENV_ROOT="$HOME/.pyenv";
        PATH="$PYENV_ROOT/bin:$PATH";
        eval "$(pyenv init -)";
        pyenv install pypy2.7-5.8.0;
        pyenv global pypy2.7-5.8.0;
      fi
    - if [[ "$TRAVIS_PYTHON_VERSION" == "pypy3" ]]; then
        git clone https://github.com/pyenv/pyenv.git ~/.pyenv;
        PYENV_ROOT="$HOME/.pyenv";
        PATH="$PYENV_ROOT/bin:$PATH";
        eval "$(pyenv init -)";
        pyenv install pypy3.5-5.8.0;
        pyenv global pypy3.5-5.8.0;
      fi

install:
  - pip install tox

script:
  - tox

cache:
  - pip

branches:
  only:
    - master
    - /^.*-maintenance$/

notifications:
  email: false
