sudo: false
language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.4
    - 3.5
env:
    - TOXENV=py-normal
    - TOXENV=py-uwsgi

matrix:
    exclude:
        - python: pypy
          env: TOXENV=py-uwsgi

install:
    # Travis uses an outdated PyPy, this installs the most recent one.
    # This makes the tests run on Travis' legacy infrastructure, but so be it.
    # temporary pyenv installation to get pypy-2.6 before container infra upgrade
    - if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
        git clone https://github.com/yyuu/pyenv.git ~/.pyenv;
        PYENV_ROOT="$HOME/.pyenv";
        PATH="$PYENV_ROOT/bin:$PATH";
        eval "$(pyenv init -)";
        pyenv install pypy-4.0.1;
        pyenv global pypy-4.0.1;
      fi
    - python --version
    - pip install tox flake8

script:
    - tox
    - make stylecheck

branches:
  except:
    - website

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
